[package]
name = "vise-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
jsonwebtoken = { version = "11", default-features = false, features = ["use_pem", "aws_lc_rs"] }
reqwest.workspace = true
serde.workspace = true
futures.workspace = true
serde_json.workspace = true
subtle = "2"
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
vise-core.workspace = true

[dev-dependencies]
async-trait.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower = { version = "0.5", features = ["util"] }
wiremock = "0.6"
