[package]
name = "vise-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
utoipa = { workspace = true }
